<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>VoiceFlowWin.VoskEngine</RootNamespace>
    <AssemblyName>VoiceFlowWin.Vosk</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vosk" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoiceFlowWin.Core\VoiceFlowWin.Core.csproj" />
  </ItemGroup>

</Project>
